# git pull git@github.com:lpaseen/meinEnigma.git master

default: upload

upload: myEnigma.ino
	${HOME}/arduino-1.8.2/arduino --upload myEnigma.ino

verify: myEnigma.ino
	${HOME}/arduino-1.8.2/arduino --verify myEnigma.ino
